### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by velocitatem** [velocitatem/HarmoniQ#2]
+ [ ] Setup server - necessary to connect Spotify API
+ [ ] Setup user flow
+ [ ] Create a simple algorithm that considers all the data
